export const LOADING_PHRASES = [
  "CREATING CONNECTIONS",
  "SPARKING IDEAS",
  "BUILDING COMMUNITIES",
  "DESIGNING EXPERIENCES",
  "INNOVATING TOGETHER",
  "AMPLIFYING VOICES",
  "CRAFTING STORIES",
  "ENGAGING AUDIENCES",
  "SHAPING DIGITAL SPACES",
  "TURNING IDEAS INTO IMPACT",
  "CONNECTING PEOPLE",
  "SOCIAL STRATEGY IN ACTION",
  "MAKING BRANDS MEMORABLE",
  "FUELING CREATIVITY",
  "DRIVING CONVERSATIONS",
  "BRINGING VISIONS TO LIFE",
];


export const LETTER_COUNT = 120;
export const BASE_RADIUS = 200;
export const MAX_RADIUS_VARIATION = 150;
